trigger:
- main

resources:
- repo: self

variables:
  imageName: 'nodejs-app:$(Build.BuildId)'

stages:
- stage: Build
  jobs:
  - job: BuildImage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        dockerfile: '**/Dockerfile'
        tags: |
          $(imageName)

- stage: Push
  jobs:
  - job: PushImage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        command: 'push'
        repository: 'myvueapp.azurecr.io/nodejs-app'
        tags: |
          $(imageName)
        containerRegistry: |
          $(dockerRegistryServiceConnection)

- stage: Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployToAKS
    environment: 'MyAKSCluster'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to AKS"
